"""Unit tests for app/services/docker_service.py — config, env export, guide text.

Probes are monkeypatched; no engine is needed.
"""
import json

import pytest

from app.services import docker_service as ds


@pytest.fixture(autouse=True)
def _tmp_config(tmp_path, monkeypatch):
    monkeypatch.setattr(ds, "DOCKER_CONFIG_FILE", tmp_path / "docker_config.json")
    monkeypatch.setattr(ds, "_LOCK", tmp_path / "docker_config.json.lock")
    yield


def test_defaults_when_missing():
    cfg = ds.load_config()
    assert cfg["mode"] == "auto"
    assert cfg["host"] == ""
    assert ds.env_overrides(cfg) == {}
    assert ds.shell_exports(cfg) == ""


def test_remote_requires_host():
    with pytest.raises(ValueError, match="docker.err.host_required"):
        ds.validate({"mode": "remote", "host": ""})
    with pytest.raises(ValueError, match="docker.err.host_format"):
        ds.validate({"mode": "remote", "host": "192.168.1.10:2375"})
    with pytest.raises(ValueError, match="docker.err.mode"):
        ds.validate({"mode": "yolo"})
    with pytest.raises(ValueError, match="docker.err.cert_path"):
        ds.validate({"mode": "remote", "host": "tcp://h:2376", "cert_path": "certs"})


def test_save_and_export_remote():
    cfg = ds.save_config({"mode": "remote", "host": "tcp://host.docker.internal:2375"})
    assert cfg["updated_at"]
    on_disk = json.loads(ds.DOCKER_CONFIG_FILE.read_text())
    assert on_disk["mode"] == "remote"
    # all three keys, empty = unset (sandbox overlay leaves TLS vars behind)
    assert ds.env_overrides() == {"DOCKER_HOST": "tcp://host.docker.internal:2375",
                                  "DOCKER_TLS_VERIFY": "", "DOCKER_CERT_PATH": ""}
    assert ds.shell_exports() == ("export DOCKER_HOST='tcp://host.docker.internal:2375'\n"
                                  "unset DOCKER_TLS_VERIFY\nunset DOCKER_CERT_PATH\n")
    env = ds.apply_overrides({"DOCKER_TLS_VERIFY": "1", "DOCKER_CERT_PATH": "/docker-certs/client",
                              "HOME": "/root"}, ds.env_overrides())
    assert env == {"DOCKER_HOST": "tcp://host.docker.internal:2375", "HOME": "/root"}

    cfg = ds.save_config({"mode": "remote", "host": "tcp://10.0.0.5:2376",
                          "tls_verify": True, "cert_path": "/docker-certs/client"})
    env = ds.env_overrides(cfg)
    assert env == {"DOCKER_HOST": "tcp://10.0.0.5:2376", "DOCKER_TLS_VERIFY": "1",
                   "DOCKER_CERT_PATH": "/docker-certs/client"}


def test_off_adds_nothing_and_skips_probe(monkeypatch):
    ds.save_config({"mode": "off"})
    monkeypatch.setattr(ds, "probe_via_bridge", lambda *a, **k: pytest.fail("must not probe"))
    st = ds.status()
    assert st["mode"] == "off" and st["probe_source"] == "skipped" and not st["reachable"]
    assert ds.claude_md(st) == ""


def test_overlay_classification():
    assert ds.overlay_of("") == "none"
    assert ds.overlay_of("tcp://sandbox:2376") == "sandbox"
    assert ds.overlay_of("unix:///var/run/docker.sock") == "socket"
    assert ds.overlay_of("tcp://host.docker.internal:2375") == "remote"


def test_status_prefers_bridge(monkeypatch):
    monkeypatch.setattr(ds, "probe_via_bridge", lambda overrides, **k: {
        "ok": True, "docker_host": "unix:///var/run/docker.sock",
        "engine": {"name": "Docker Engine - Community", "version": "29.6.1",
                   "api_version": "1.55", "os": "linux", "arch": "amd64"},
        "projects_host_dir": "/home/user/ili", "error": ""})
    monkeypatch.setattr(ds, "probe_via_api", lambda *a, **k: pytest.fail("bridge answered"))
    st = ds.status()
    assert st["reachable"] and st["probe_source"] == "terminal" and st["overlay"] == "socket"
    md = ds.claude_md(st)
    assert md.startswith("# Project containers (generated by ili")
    assert "/home/user/ili/projects/<board>:/app" in md          # host path rule
    assert "8100" in md and "8119" in md                          # port range


def test_status_falls_back_to_api(monkeypatch):
    ds.save_config({"mode": "remote", "host": "tcp://h:2375"})
    monkeypatch.setattr(ds, "probe_via_bridge", lambda *a, **k: None)
    seen = {}

    def fake_api(host, tls_verify=False, cert_path="", timeout=0):
        seen["host"] = host
        return {"ok": False, "docker_host": host, "engine": None, "error": "ConnectError: refused"}

    monkeypatch.setattr(ds, "probe_via_api", fake_api)
    st = ds.status()
    assert seen["host"] == "tcp://h:2375"
    assert st["probe_source"] == "api" and not st["reachable"] and "refused" in st["error"]
    assert st["overlay"] == "remote"
    assert ds.claude_md(st) == ""  # unreachable → no guide


def test_candidate_is_not_persisted(monkeypatch):
    monkeypatch.setattr(ds, "probe_via_bridge", lambda overrides, **k: {
        "ok": True, "docker_host": overrides.get("DOCKER_HOST", ""), "engine": {"name": "Docker",
        "version": "1", "api_version": "1", "os": "linux", "arch": "amd64"}, "error": ""})
    st = ds.status(candidate={"mode": "remote", "host": "tcp://x:2375"})
    assert st["docker_host"] == "tcp://x:2375"
    assert ds.load_config()["mode"] == "auto"  # nothing written


def test_port_range_env_is_tolerant(monkeypatch):
    monkeypatch.setenv("X_PORT", "abc")
    assert ds._int_env("X_PORT", 8100) == 8100
    monkeypatch.setenv("X_PORT", " 8200 ")
    assert ds._int_env("X_PORT", 8100) == 8200
    monkeypatch.setenv("X_PORT", "")
    assert ds._int_env("X_PORT", 8100) == 8100


def test_guide_without_projects_host_dir_does_not_invent_a_path(monkeypatch):
    monkeypatch.setattr(ds, "probe_via_bridge", lambda overrides, **k: {
        "ok": True, "docker_host": "tcp://host.docker.internal:2375",
        "engine": {"name": "Docker Desktop", "version": "28", "api_version": "1.5", "os": "linux",
                   "arch": "amd64"}, "projects_host_dir": "", "error": ""})
    md = ds.claude_md(ds.status(candidate={"mode": "remote", "host": "tcp://host.docker.internal:2375"}))
    assert "<PROJECTS_HOST_DIR>" not in md
    assert "PROJECTS_HOST_DIR is not configured" in md
