"""Unit tests for app/services/docker_service.py — config, env export, guide text.

Probes are monkeypatched; no engine is needed.
"""
import json
import urllib.error

import pytest

from app.services import docker_service as ds


class _FakeResponse:
    """Minimal stand-in for the context manager urllib.request.urlopen() returns."""

    def __init__(self, body: dict):
        self._body = json.dumps(body).encode("utf-8")

    def read(self):
        return self._body

    def __enter__(self):
        return self

    def __exit__(self, *a):
        return False


@pytest.fixture(autouse=True)
def _tmp_config(tmp_path, monkeypatch):
    monkeypatch.setattr(ds, "DOCKER_CONFIG_FILE", tmp_path / "docker_config.json")
    monkeypatch.setattr(ds, "_LOCK", tmp_path / "docker_config.json.lock")
    yield


def test_defaults_when_missing():
    cfg = ds.load_config()
    assert cfg["mode"] == "auto"
    assert cfg["host"] == ""
    assert ds.env_overrides(cfg) == {}
    assert ds.shell_exports(cfg) == ""


def test_remote_requires_host():
    with pytest.raises(ValueError, match="docker.err.host_required"):
        ds.validate({"mode": "remote", "host": ""})
    with pytest.raises(ValueError, match="docker.err.host_format"):
        ds.validate({"mode": "remote", "host": "192.168.1.10:2375"})
    with pytest.raises(ValueError, match="docker.err.mode"):
        ds.validate({"mode": "yolo"})
    with pytest.raises(ValueError, match="docker.err.cert_path"):
        ds.validate({"mode": "remote", "host": "tcp://h:2376", "cert_path": "certs"})


def test_save_and_export_remote():
    cfg = ds.save_config({"mode": "remote", "host": "tcp://host.docker.internal:2375"})
    assert cfg["updated_at"]
    on_disk = json.loads(ds.DOCKER_CONFIG_FILE.read_text())
    assert on_disk["mode"] == "remote"
    # all three keys, empty = unset (sandbox overlay leaves TLS vars behind)
    assert ds.env_overrides() == {"DOCKER_HOST": "tcp://host.docker.internal:2375",
                                  "DOCKER_TLS_VERIFY": "", "DOCKER_CERT_PATH": ""}
    assert ds.shell_exports() == ("export DOCKER_HOST='tcp://host.docker.internal:2375'\n"
                                  "unset DOCKER_TLS_VERIFY\nunset DOCKER_CERT_PATH\n")
    env = ds.apply_overrides({"DOCKER_TLS_VERIFY": "1", "DOCKER_CERT_PATH": "/docker-certs/client",
                              "HOME": "/root"}, ds.env_overrides())
    assert env == {"DOCKER_HOST": "tcp://host.docker.internal:2375", "HOME": "/root"}

    cfg = ds.save_config({"mode": "remote", "host": "tcp://10.0.0.5:2376",
                          "tls_verify": True, "cert_path": "/docker-certs/client"})
    env = ds.env_overrides(cfg)
    assert env == {"DOCKER_HOST": "tcp://10.0.0.5:2376", "DOCKER_TLS_VERIFY": "1",
                   "DOCKER_CERT_PATH": "/docker-certs/client"}


def test_off_adds_nothing_and_skips_probe(monkeypatch):
    ds.save_config({"mode": "off"})
    monkeypatch.setattr(ds, "probe_via_bridge", lambda *a, **k: pytest.fail("must not probe"))
    st = ds.status()
    assert st["mode"] == "off" and st["probe_source"] == "skipped" and not st["reachable"]
    assert ds.claude_md(st) == ""


def test_overlay_classification():
    assert ds.overlay_of("") == "none"
    assert ds.overlay_of("tcp://sandbox:2376") == "sandbox"
    assert ds.overlay_of("unix:///var/run/docker.sock") == "socket"
    assert ds.overlay_of("tcp://host.docker.internal:2375") == "desktop"
    assert ds.overlay_of("tcp://10.0.0.5:2376") == "remote"


def test_status_prefers_bridge(monkeypatch):
    monkeypatch.setattr(ds, "probe_via_bridge", lambda overrides, **k: {
        "ok": True, "docker_host": "unix:///var/run/docker.sock",
        "engine": {"name": "Docker Engine - Community", "version": "29.6.1",
                   "api_version": "1.55", "os": "linux", "arch": "amd64"},
        "projects_host_dir": "/home/user/ili", "error": ""})
    monkeypatch.setattr(ds, "probe_via_api", lambda *a, **k: pytest.fail("bridge answered"))
    st = ds.status()
    assert st["reachable"] and st["probe_source"] == "terminal" and st["overlay"] == "socket"
    md = ds.claude_md(st)
    assert md.startswith("# Project containers (generated by ili")
    assert "/home/user/ili/projects/<board>:/app" in md          # host path rule
    assert "8100" in md and "8119" in md                          # port range


def test_status_falls_back_to_api(monkeypatch):
    ds.save_config({"mode": "remote", "host": "tcp://h:2375"})
    monkeypatch.setattr(ds, "probe_via_bridge", lambda *a, **k: None)
    seen = {}

    def fake_api(host, tls_verify=False, cert_path="", timeout=0):
        seen["host"] = host
        return {"ok": False, "docker_host": host, "engine": None, "error": "ConnectError: refused"}

    monkeypatch.setattr(ds, "probe_via_api", fake_api)
    st = ds.status()
    assert seen["host"] == "tcp://h:2375"
    assert st["probe_source"] == "api" and not st["reachable"] and "refused" in st["error"]
    assert st["overlay"] == "remote"
    # unreachable is not the same as off: the guide now says so instead of
    # disappearing, otherwise the AI finds nothing and assumes docker works
    # (F-02 of the 0.1.22 test report).
    guide = ds.claude_md(st)
    assert "No container engine is available" in guide
    assert "refused" in guide          # names the actual reason
    assert "no setup needed" not in guide


def test_candidate_is_not_persisted(monkeypatch):
    monkeypatch.setattr(ds, "probe_via_bridge", lambda overrides, **k: {
        "ok": True, "docker_host": overrides.get("DOCKER_HOST", ""), "engine": {"name": "Docker",
        "version": "1", "api_version": "1", "os": "linux", "arch": "amd64"}, "error": ""})
    st = ds.status(candidate={"mode": "remote", "host": "tcp://x:2375"})
    assert st["docker_host"] == "tcp://x:2375"
    assert ds.load_config()["mode"] == "auto"  # nothing written


def test_port_range_env_is_tolerant(monkeypatch):
    monkeypatch.setenv("X_PORT", "abc")
    assert ds._int_env("X_PORT", 8100) == 8100
    monkeypatch.setenv("X_PORT", " 8200 ")
    assert ds._int_env("X_PORT", 8100) == 8200
    monkeypatch.setenv("X_PORT", "")
    assert ds._int_env("X_PORT", 8100) == 8100


def test_guide_without_projects_host_dir_does_not_invent_a_path(monkeypatch):
    monkeypatch.setattr(ds, "probe_via_bridge", lambda overrides, **k: {
        "ok": True, "docker_host": "tcp://host.docker.internal:2375",
        "engine": {"name": "Docker Desktop", "version": "28", "api_version": "1.5", "os": "linux",
                   "arch": "amd64"}, "projects_host_dir": "", "error": ""})
    md = ds.claude_md(ds.status(candidate={"mode": "remote", "host": "tcp://host.docker.internal:2375"}))
    assert "<PROJECTS_HOST_DIR>" not in md
    assert "PROJECTS_HOST_DIR is not configured" in md


# ── auto: Docker Desktop fallback (F-24) and honest guide (F-21), test report 0.2.0 ──

_DESKTOP = "tcp://host.docker.internal:2375"
_ENGINE = {"name": "Docker Desktop 4.91.0 (239619)", "version": "29.8.0", "api_version": "1.56",
           "os": "linux", "arch": "amd64"}


def _bridge(answers: dict, calls: list | None = None):
    """Fake probe_via_bridge: answer by DOCKER_HOST override ('' = the overlay)."""
    def probe(overrides, **k):
        host = (overrides or {}).get("DOCKER_HOST", "")
        if calls is not None:
            calls.append(host)
        ok = answers.get(host, False)
        return {"ok": ok, "docker_host": host, "engine": _ENGINE if ok else None,
                "projects_host_dir": "/run/desktop/mnt/host/c/Users/u/ili" if ok else "",
                "error": "" if ok else f"no engine at {host or 'socket'}"}
    return probe


def test_auto_finds_docker_desktop_and_exports_it(monkeypatch):
    calls = []
    monkeypatch.setattr(ds, "probe_via_bridge", _bridge({_DESKTOP: True}, calls))
    st = ds.status()
    assert calls == ["", _DESKTOP]                       # overlay first, Desktop second
    assert st["reachable"] and st["overlay"] == "desktop" and st["docker_host"] == _DESKTOP
    assert ds.load_config()["detected_host"] == _DESKTOP
    assert ds.env_overrides() == {"DOCKER_HOST": _DESKTOP, "DOCKER_TLS_VERIFY": "",
                                  "DOCKER_CERT_PATH": ""}
    assert ds.shell_exports().startswith(f"export DOCKER_HOST='{_DESKTOP}'")
    md = ds.claude_md(st)
    assert "No container engine" not in md
    assert "/run/desktop/mnt/host/c/Users/u/ili/projects/<board>:/app" in md
    assert "`ili-*` are ili itself" in md                # same engine that runs ili
    assert "curl http://host.docker.internal:<port>/" in md


def test_auto_prefers_overlay_and_forgets_old_detection(monkeypatch):
    ds.DOCKER_CONFIG_FILE.write_text(json.dumps({"mode": "auto", "detected_host": _DESKTOP}))
    calls = []
    monkeypatch.setattr(ds, "probe_via_bridge", _bridge({"": True}, calls))
    st = ds.status()
    assert calls == [""]                                 # Desktop not even tried
    assert st["reachable"] and ds.load_config()["detected_host"] == ""
    assert ds.env_overrides() == {}                      # overlay env stays untouched


def test_auto_nothing_answers(monkeypatch):
    ds.DOCKER_CONFIG_FILE.write_text(json.dumps({"mode": "auto", "detected_host": _DESKTOP}))
    monkeypatch.setattr(ds, "probe_via_bridge", _bridge({}))
    st = ds.status()
    assert not st["reachable"] and st["overlay"] == "none"
    assert st["error"] == "no engine at socket"          # the overlay's reason, not the Desktop miss
    assert ds.load_config()["detected_host"] == ""
    assert "No container engine is available" in ds.claude_md(st)


def test_auto_desktop_probe_can_be_disabled(monkeypatch):
    monkeypatch.setattr(ds, "DESKTOP_HOSTS", ())
    calls = []
    monkeypatch.setattr(ds, "probe_via_bridge", _bridge({_DESKTOP: True}, calls))
    assert not ds.status()["reachable"] and calls == [""]


def test_detected_host_is_not_user_input(monkeypatch):
    cfg = ds.save_config({"mode": "auto", "detected_host": "tcp://evil:2375"})
    assert cfg["detected_host"] == ""
    ds.DOCKER_CONFIG_FILE.write_text(json.dumps({"mode": "auto", "detected_host": _DESKTOP}))
    assert ds.save_config({"mode": "remote", "host": "tcp://h:2375"})["detected_host"] == ""


def test_test_button_does_not_store_detection(monkeypatch):
    monkeypatch.setattr(ds, "probe_via_bridge", _bridge({_DESKTOP: True}))
    assert ds.status(candidate={"mode": "auto"})["reachable"]
    assert ds.load_config()["detected_host"] == ""


def test_claude_md_route_says_no_engine_with_200(monkeypatch):
    """F-21: 503 made ili-docker-guide keep an old 'no setup needed' guide."""
    from app.api import docker_config
    monkeypatch.setattr(ds, "probe_via_bridge", _bridge({}))
    monkeypatch.setattr(ds, "DESKTOP_HOSTS", ())
    res = docker_config.get_claude_md()
    body = res if isinstance(res, str) else res.body.decode()
    assert getattr(res, "status_code", 200) == 200
    assert "No container engine is available" in body


# ── MCP server for container control (Settings → Docker → MCP switch) ─────────

def test_mcp_status_ok(monkeypatch):
    monkeypatch.setattr(ds.urllib.request, "urlopen",
                        lambda req, timeout=0: _FakeResponse({"script_present": True, "configured": True}))
    assert ds.mcp_status() == {"script_present": True, "configured": True}


def test_mcp_status_old_terminal_image(monkeypatch):
    def raise_404(req, timeout=0):
        raise urllib.error.HTTPError(req.full_url, 404, "not found", {}, None)
    monkeypatch.setattr(ds.urllib.request, "urlopen", raise_404)
    st = ds.mcp_status()
    assert st == {"script_present": False, "configured": False, "error": "terminal_outdated"}


def test_mcp_status_terminal_unreachable(monkeypatch):
    def raise_url_error(req, timeout=0):
        raise urllib.error.URLError("connection refused")
    monkeypatch.setattr(ds.urllib.request, "urlopen", raise_url_error)
    st = ds.mcp_status()
    assert st["error"] == "terminal_unreachable" and not st["configured"]


def test_mcp_setup_and_remove_post_to_bridge(monkeypatch):
    calls = []

    def fake_urlopen(req, timeout=0):
        calls.append(req.full_url)
        return _FakeResponse({"ok": True, "already": False})
    monkeypatch.setattr(ds.urllib.request, "urlopen", fake_urlopen)
    assert ds.mcp_setup() == {"ok": True, "already": False}
    assert ds.mcp_remove() == {"ok": True, "already": False}
    assert calls == [f"{ds.CLAUDE_BRIDGE_URL}/mcp/docker/setup", f"{ds.CLAUDE_BRIDGE_URL}/mcp/docker/remove"]
