#!/usr/bin/env bash
# ili-docker-guide.sh — keeps /projects/CLAUDE.md in sync with GET /api/docker/claude-md.
#
# /projects is the parent of every board folder, and Claude Code loads CLAUDE.md
# files from parent directories — so this one file tells every Claude session
# (terminal AND automat) how project containers work here: DOCKER_HOST, host paths
# for bind mounts, the port range. Content comes from the api (single source:
# app/services/docker_service.claude_md); an empty answer means "remove".
#
# Marker-guarded: the script only writes or removes a file it generated itself.
# A CLAUDE.md a user put there by hand is never touched.
#
# Called by ili-claude (terminal, before Claude starts) and by the automat worker
# (before each `claude -p`). Usage: ili-docker-guide [API_URL]
set -uo pipefail

API="${1:-${ILI_API_URL:-http://api:8798}}"
PROJECTS="${PROJECTS_DIR:-/projects}"
TARGET="${PROJECTS}/CLAUDE.md"
MARKER="# Project containers (generated by ili"

log() { echo "[ili-docker-guide] $*" >&2; }

if [[ ! -d "$PROJECTS" ]]; then
    log "no ${PROJECTS} directory — nothing to do"
    exit 0
fi
if ! command -v curl >/dev/null 2>&1; then
    log "curl missing — cannot fetch the guide"
    exit 0
fi

body="$(curl -fsS --max-time 6 "${API}/api/docker/claude-md" 2>/dev/null)"
rc=$?
if [[ $rc -ne 0 ]]; then
    log "api ${API} not reachable (curl exit ${rc}) — leaving ${TARGET} as is"
    exit 0
fi

if [[ -f "$TARGET" ]] && ! head -n 1 "$TARGET" | grep -qF "$MARKER"; then
    log "${TARGET} was not generated by ili — leaving it alone"
    exit 0
fi

if [[ -z "$body" ]]; then
    if [[ -f "$TARGET" ]]; then
        rm -f "$TARGET" && log "removed ${TARGET} (Docker off or not reachable)"
    fi
    exit 0
fi

if [[ -f "$TARGET" ]] && [[ "$(cat "$TARGET")" == "$body" ]]; then
    exit 0  # unchanged
fi

if printf '%s\n' "$body" > "$TARGET"; then
    log "wrote ${TARGET} ($(printf '%s' "$body" | wc -l | tr -d ' ') lines)"
else
    log "cannot write ${TARGET}"
fi
exit 0
