#!/bin/sh
# nginx-setup.sh — prepares the web container before nginx starts.
#
# Three jobs:
#   1. wait until the `api` service resolves, then write /etc/nginx/ili-api-upstream.conf
#      (included by nginx-portable.conf before _api-locations.conf) with a resolver +
#      a $api_backend variable — a *static* proxy_pass target resolves once at nginx
#      startup and is cached for the worker's lifetime, so restarting only the `api`
#      container (new IP in the compose network) leaves nginx proxying to a dead IP
#      until the web container itself restarts. The variable form forces nginx to
#      re-resolve via the `resolver` directive instead (found 07.09.2026, v0.1.16).
#   2. write /etc/nginx/ili-projterm.conf (included by the server block in
#      nginx-portable.conf) — either the real terminal proxy or a stub that
#      explains how to enable it. Without that file nginx would refuse to start.
#      Reuses the same resolver detection from job 1.
#
# The terminal is opt-in through a second compose file:
#   docker compose -f docker-compose.yml -f docker-compose.terminal.yml up -d
# This script detects the result automatically: if the `terminal` service answers,
# the route is wired; if not, the stub is written.
#
# Why authentication lives here and not in ttyd:
#   A browser terminal is full shell access, so the gate belongs at the single
#   entrance. ttyd itself has no published port and is only reachable inside the
#   compose network. Two layers of Basic auth would also break the WebSocket in
#   Safari, which does not send Basic credentials during the WS handshake — that
#   is why the WS path is protected by a cookie that this route hands out after a
#   successful login.
#
# Debug: docker compose logs web | grep ili-setup
set -eu

log() { echo "[ili-setup] $*"; }

LOCATIONS_FILE=/etc/nginx/ili-projterm.conf
MAP_FILE=/etc/nginx/conf.d/00-ili-projterm-map.conf
HTPASSWD_FILE=/etc/nginx/ili-terminal.htpasswd
RESOLVER_CONF=/etc/nginx/conf.d/00-ili-resolver.conf
API_UPSTREAM_FILE=/etc/nginx/ili-api-upstream.conf

TERMINAL_HOST="${TERMINAL_HOST:-terminal}"
TERMINAL_PORT="${TERMINAL_PORT:-7690}"
TERMINAL_USER="${TERMINAL_USER:-ili}"
TERMINAL_PASSWORD="${TERMINAL_PASSWORD:-}"
TERMINAL_WAIT="${TERMINAL_WAIT:-20}"
API_HOST="${API_HOST:-api}"
API_PORT="${API_PORT:-8798}"
API_WAIT="${API_WAIT:-30}"

# Older podman-compose versions (e.g. 1.0.3 in Debian 12) pass values like
# "${TERMINAL_PASSWORD:-}" through literally instead of substituting them. Taking
# that literal as the password would lock the user out of a terminal whose
# password nobody knows.
case "$TERMINAL_PASSWORD" in
    '${'*) log "WARN: TERMINAL_PASSWORD arrived unsubstituted (old compose version) — treating it as unset"
           TERMINAL_PASSWORD="" ;;
esac
case "$TERMINAL_USER" in
    '${'*|'') TERMINAL_USER="ili" ;;
esac

# --- 1) Wait for the API ------------------------------------------------------
i=0
while [ "$i" -lt "$API_WAIT" ]; do
    if wget -q -T 2 -O /dev/null "http://${API_HOST}:${API_PORT}/boards" 2>/dev/null; then
        log "api reachable at ${API_HOST}:${API_PORT}"
        break
    fi
    i=$((i + 1))
    sleep 1
done
[ "$i" -ge "$API_WAIT" ] && log "WARN: ${API_HOST}:${API_PORT} did not answer within ${API_WAIT}s — nginx may fail to resolve it"

# --- 2) Dynamic upstream resolution (api + terminal share one resolver) ------
# A static `proxy_pass http://api:8798;` is resolved once when nginx starts and
# cached for the worker's lifetime — restarting only the `api` container hands it
# a new IP in the compose network, and every /api/ request then 502s until the web
# container itself restarts too. A `resolver` directive plus a variable in
# proxy_pass forces nginx to re-resolve per request instead. Docker's embedded DNS
# (127.0.0.11) and Podman's aardvark-dns are both listed in /etc/resolv.conf, so
# reading it beats hardcoding either address.
RESOLVER="$(awk '/^nameserver/ {print $2; exit}' /etc/resolv.conf 2>/dev/null || true)"
if [ -n "$RESOLVER" ]; then
    log "using resolver ${RESOLVER} for dynamic upstream resolution"
    # http-level, shared by every server block (default.conf + whatever else lands
    # in conf.d/) — defining it once here avoids a duplicate "resolver" directive
    # error if it also had to be declared inside the api/terminal location files.
    cat > "$RESOLVER_CONF" <<EOF
# Generated by ili-setup — do not edit, changes are overwritten.
resolver ${RESOLVER} valid=10s ipv6=off;
EOF
else
    log "WARN: no nameserver in /etc/resolv.conf — static api upstream, restart web after restarting api"
    rm -f "$RESOLVER_CONF"
fi
cat > "$API_UPSTREAM_FILE" <<EOF
# Generated by ili-setup — do not edit, changes are overwritten.
set \$api_backend "http://${API_HOST}:${API_PORT}";
EOF

# The map directive lives at http level; conf.d/*.conf is included there. It must
# exist even when the terminal is off, because the locations file may reference it.
write_map() {
    cat > "$MAP_FILE" <<EOF
# Generated by ili-setup — do not edit, changes are overwritten.
map \$cookie_ili_term \$ili_term_ok {
    default        0;
    "${1}"         1;
}
EOF
}

write_stub() {
    write_map "disabled"
    cat > "$LOCATIONS_FILE" <<'EOF'
# Generated by ili-setup — project terminal is NOT running.
location ^~ /projterm/ {
    default_type text/plain;
    return 503 "ili project terminal is not enabled.\n\nStart it with:\n    docker compose -f docker-compose.yml -f docker-compose.terminal.yml up -d\n\nAlready ran that? Then this web container was started before the terminal\nexisted and still carries the old configuration. Add:\n    docker compose -f docker-compose.yml -f docker-compose.terminal.yml restart web\n\nSee docs/PROJECT-TERMINAL.md for details.\n";
}
EOF
    log "terminal not reachable — wrote 503 stub to ${LOCATIONS_FILE}"
}

# --- Is the terminal service running? ---------------------------------------
# Both compose implementations start services concurrently, so give the terminal
# a moment to come up before deciding. wget is part of busybox in nginx:alpine.
probe() {
    i=0
    while [ "$i" -lt "$TERMINAL_WAIT" ]; do
        if wget -q -T 2 -O /dev/null "http://${TERMINAL_HOST}:${TERMINAL_PORT}/projterm/token" 2>/dev/null; then
            return 0
        fi
        i=$((i + 1))
        sleep 1
    done
    return 1
}

log "probing http://${TERMINAL_HOST}:${TERMINAL_PORT}/projterm/token (up to ${TERMINAL_WAIT}s)"
if probe; then
    log "terminal service is up"
elif nslookup "$TERMINAL_HOST" > /dev/null 2>&1; then
    # The name resolves, so the service exists but is still booting (typical after
    # a host reboot, when both containers come up at once). Wiring the route anyway
    # is safe: the upstream is re-resolved per request, so it starts working as
    # soon as ttyd listens. Writing the stub instead would leave a 503 behind that
    # only a restart of this container could clear.
    log "terminal not answering yet but resolvable — wiring the route anyway"
else
    write_stub
    exit 0
fi

# --- Credentials -------------------------------------------------------------
# Decision 2026-08-16: the terminal is always behind a password. If none is
# configured, generate one on first start and print it into the startup log.
GENERATED=0
if [ -z "$TERMINAL_PASSWORD" ]; then
    TERMINAL_PASSWORD="$(head -c 32 /dev/urandom | base64 | tr -dc 'A-Za-z0-9' | cut -c1-16)"
    GENERATED=1
fi

# The nginx image ships no htpasswd tool, but nginx accepts RFC 2307 hashes in
# auth_basic_user_file. "{SHA}" = base64(sha1(password)) can be built with busybox,
# so the password does not have to sit on disk in clear text. "{PLAIN}" stays as a
# fallback for images without sha1sum/xxd.
HASH="$(printf '%s' "$TERMINAL_PASSWORD" | sha1sum 2>/dev/null | cut -d' ' -f1 | xxd -r -p 2>/dev/null | base64 2>/dev/null || true)"
if [ -n "$HASH" ]; then
    printf '%s:{SHA}%s\n' "$TERMINAL_USER" "$HASH" > "$HTPASSWD_FILE"
else
    log "WARN: sha1sum/xxd/base64 missing — storing the password in clear text"
    printf '%s:{PLAIN}%s\n' "$TERMINAL_USER" "$TERMINAL_PASSWORD" > "$HTPASSWD_FILE"
fi
# The worker processes run as an unprivileged user and must be able to read the
# file — root-only (600) makes every login fail with a 500.
chmod 640 "$HTPASSWD_FILE"
NGINX_GROUP="$(awk '/^user[[:space:]]/ {gsub(";","",$2); print $2}' /etc/nginx/nginx.conf 2>/dev/null | head -1)"
chown "root:${NGINX_GROUP:-nginx}" "$HTPASSWD_FILE" 2>/dev/null \
    || { log "WARN: cannot chown ${HTPASSWD_FILE} — falling back to world-readable"; chmod 644 "$HTPASSWD_FILE"; }

# Secret handed to the browser as a cookie after a successful Basic auth, then
# required on the WebSocket path (Safari-proof, see header comment).
WS_SECRET="$(head -c 32 /dev/urandom | base64 | tr -dc 'A-Za-z0-9' | cut -c1-24)"
write_map "$WS_SECRET"

# Same re-resolution problem and the same $RESOLVER detected in step 2 above —
# reused here instead of re-detected so both upstreams agree, and no second
# `resolver` directive gets emitted (nginx rejects a context with two of them).
if [ -n "$RESOLVER" ]; then
    UPSTREAM_LINE="set \$ili_term_upstream \"http://${TERMINAL_HOST}:${TERMINAL_PORT}\";
    proxy_pass \$ili_term_upstream\$request_uri;"
else
    UPSTREAM_LINE="proxy_pass http://${TERMINAL_HOST}:${TERMINAL_PORT};"
fi

# Der Zustand des Passworts ist hier bereits bekannt — als winziger Endpunkt
# ausgegeben, damit das Dashboard einen Hinweis zeigen kann, solange ein
# generiertes Passwort gilt. Bewusst OHNE Auth lesbar (sonst koennte die
# Oberflaeche ihn nicht abfragen) und bewusst ohne jede weitere Information:
# er sagt nur, OB personalisiert wurde, nie was.
STATE_JSON='{"generated":true}'
[ "$GENERATED" = "1" ] || STATE_JSON='{"generated":false}'

cat > "$LOCATIONS_FILE" <<EOF
# Generated by ili-setup — do not edit, changes are overwritten.
# resolver directive: see conf.d/00-ili-resolver.conf (shared with $api_backend).

# Exakte Location schlaegt das ^~-Praefix darunter — daher ohne Passwortabfrage.
location = /projterm/state {
    default_type application/json;
    add_header Cache-Control "no-store";
    return 200 '${STATE_JSON}';
}

# Relative redirect: an absolute one would drop a non-default port from the URL.
location = /projterm {
    absolute_redirect off;
    return 301 /projterm/;
}

# WebSocket: no Basic auth challenge here (Safari does not send credentials in a
# WS handshake) — the cookie handed out by the HTML route below is the proof.
location = /projterm/ws {
    if (\$ili_term_ok = 0) { return 403; }

    ${UPSTREAM_LINE}
    proxy_http_version 1.1;
    proxy_set_header Upgrade \$http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host \$host;
    proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
    proxy_read_timeout 7d;
    proxy_send_timeout 7d;
    proxy_buffering off;
}

# Terminal UI. ^~ keeps the generic .html/.js/.css regex location from stealing it.
location ^~ /projterm/ {
    auth_basic "ili project terminal";
    auth_basic_user_file ${HTPASSWD_FILE};

    # Browsers suppress the Basic-auth dialog inside an iframe and render the
    # response body instead — a board page would otherwise show nginx' raw "401
    # Authorization Required". A file-based error_page keeps the 401 status and the
    # WWW-Authenticate header, so opening /projterm/ in a tab still prompts.
    error_page 401 /ili-terminal-login.html;

    # Only sent on a successful (2xx/3xx) response, i.e. after the login.
    add_header Set-Cookie "ili_term=${WS_SECRET}; Path=/projterm; HttpOnly; SameSite=Strict";
    add_header Cache-Control "no-store";

    ${UPSTREAM_LINE}
    proxy_http_version 1.1;
    proxy_set_header Host \$host;
    proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
}
EOF

log "wired /projterm/ -> ${TERMINAL_HOST}:${TERMINAL_PORT} (user=${TERMINAL_USER})"

if [ "$GENERATED" = "1" ]; then
    log ""
    log "================ ili project terminal ================"
    log " The terminal gives full shell access and is password"
    log " protected. No password was configured, so one was"
    log " generated for this start:"
    log ""
    log "   user:     ${TERMINAL_USER}"
    log "   password: ${TERMINAL_PASSWORD}"
    log ""
    log " It changes on every restart. Put TERMINAL_PASSWORD"
    log " into your .env to keep a stable one."
    log "====================================================="
    log ""
else
    log "using TERMINAL_PASSWORD from the environment"
fi
